name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  ci:
    name: Build & Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      security-events: write
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'rostooling-languages/package-lock.json'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Setup RosTooling Catalogues
        run: |
          mkdir -p $HOME/.rostooling/catalogue_repos
          git clone --depth 1 https://github.com/ipa-nhg/RosModelsCatalog.git $HOME/.rostooling/catalogue_repos/RosModelsCatalog
          git clone --depth 1 https://github.com/ipa320/RosCommonObjects.git $HOME/.rostooling/catalogue_repos/RosCommonObjects
          echo '{"customFolders":[],"lastSyncTimestamp":'$(date +%s%3N)'}' > $HOME/.rostooling/catalogue_repos/catalogue_config.json

      - name: Install dependencies
        working-directory: rostooling-languages
        run: |
          npm ci
          npm install --no-save @microsoft/eslint-formatter-sarif@3.1.0

      - name: Build Language Server JAR
        run: ./gradlew :rostooling-languages:copyFatJar
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GPR_KEY || secrets.GITHUB_TOKEN }}

      - name: Compile TypeScript
        working-directory: rostooling-languages
        run: npm run compile

      - name: Run ESLint
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        working-directory: rostooling-languages
        run: npx eslint ./src --config eslint.config.mjs --format @microsoft/eslint-formatter-sarif --output-file eslint-results.sarif
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: rostooling-languages/eslint-results.sarif
          wait-for-processing: true

      - name: Run VS Code Extension Tests
        working-directory: rostooling-languages
        run: xvfb-run -a npm test
        env:
          ROSTOOLING_CATALOGUE_PATH: /home/runner/.rostooling/catalogue_repos
